package httpapi

const indexPage = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>农产品分级包装屏</title>
<style>
:root{font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#18302b;background:#f3f7f2}body{margin:0}header{background:#173f35;color:white;padding:22px 32px;display:flex;justify-content:space-between;align-items:center}h1{font-size:25px;margin:0}.sub{opacity:.75;font-size:13px}.wrap{max-width:1280px;margin:0 auto;padding:24px}.metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:12px}.metric{background:white;border:1px solid #d6e3dc;border-radius:6px;padding:16px}.metric strong{display:block;font-size:29px;color:#17624d}.metric span{font-size:12px;color:#667b72}.grid{display:grid;grid-template-columns:2fr 1fr;gap:16px;margin-top:18px}.panel{background:white;border:1px solid #d6e3dc;border-radius:6px;padding:18px}.panel h2{font-size:16px;margin:0 0 12px}.bar{height:12px;background:#e5eee9;border-radius:2px;overflow:hidden}.fill{height:100%;background:#e68645}.rows{height:270px;overflow:hidden}.row{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #edf2ef;font-size:13px}.line{display:flex;align-items:center;justify-content:space-between;padding:10px 0}.dot{width:9px;height:9px;border-radius:50%;display:inline-block;margin-right:8px;background:#3ca370}.dot.stop{background:#d35c4e}@media(max-width:900px){.metrics{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr}}@media(max-width:560px){.wrap{padding:14px}.metrics{grid-template-columns:repeat(2,1fr)}header{padding:18px}}
</style></head><body><header><div><h1>农产品分级包装屏</h1><div class="sub">实时班次看板 · 分级与装箱状态</div></div><div id="clock" class="sub">加载中</div></header><main class="wrap"><section class="metrics"><div class="metric"><strong id="pending">0</strong><span>待分级 kg</span></div><div class="metric"><strong id="one">0</strong><span>一级品 kg</span></div><div class="metric"><strong id="two">0</strong><span>二级品 kg</span></div><div class="metric"><strong id="loss">0</strong><span>损耗 kg</span></div><div class="metric"><strong id="packed">0</strong><span>已装箱</span></div><div class="metric"><strong id="stopped">0</strong><span>停机设备</span></div></section><section class="grid"><div class="panel"><h2>装箱进度</h2><div id="progress"></div><h2 style="margin-top:22px">滚动明细</h2><div id="audits" class="rows"></div></div><div class="panel"><h2>设备状态</h2><div id="lines"></div><h2 style="margin-top:24px">班组提示</h2><p class="sub">停机时先处理设备状态，再继续提交装箱进度。所有操作会记录审计明细。</p></div></section></main><script>
const $=id=>document.getElementById(id);function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function refresh(){const r=await fetch('/api/dashboard');if(!r.ok)return;const d=await r.json(),s=d.snapshot;$('pending').textContent=s.pending_kg;$('one').textContent=s.grade_one_kg;$('two').textContent=s.grade_two_kg;$('loss').textContent=s.loss_kg;$('packed').textContent=s.packed_boxes;$('stopped').textContent=s.stopped_lines;$('audits').innerHTML=(d.audits||[]).map(a=>'<div class="row"><span>'+esc(a.action)+' · '+esc(a.actor)+'</span><span class="sub">'+esc(a.detail)+'</span></div>').join('');const p=await fetch('/api/progress').then(x=>x.json());$('progress').innerHTML=(p.items||[]).map(x=>{const n=x.target_boxes?Math.round(x.boxes/x.target_boxes*100):0;return '<div class="row"><span>'+esc(x.batch_id)+' / '+esc(x.line_id)+'</span><span>'+x.boxes+'/'+x.target_boxes+'</span><div style="width:100px"><div class="bar"><div class="fill" style="width:'+n+'%"></div></div></div></div>'}).join('')||'<div class="sub">暂无装箱任务</div>';const l=await fetch('/api/lines').then(x=>x.json());$('lines').innerHTML=(l.items||[]).map(x=>'<div class="line"><span><i class="dot '+(x.stopped?'stop':'')+'"></i>'+esc(x.name||x.id)+'</span><span class="sub">'+(x.stopped?esc(x.reason):'运行中')+'</span></div>').join('')||'<div class="sub">暂无设备</div>'}$('clock').textContent=new Date().toLocaleTimeString();refresh();setInterval(()=>{refresh();$('clock').textContent=new Date().toLocaleTimeString()},5000)
</script></body></html>`
